### ISSUE TITLE
Update dependencies from NetBeans RELEASE82 to RELEASE90

### ISSUE THREAD

**Issue by mcallisto** [gephi/gephi-toolkit#39]
@eduramiba Is it possible for you to adjust the dependencies from NetBeans RELEASE82 to RELEASE90?

The current scenario seems to be:
* http://bits.netbeans.org/nexus/content/groups/netbeans/ has been often down recently, probably caught in the middle between the switch from Oracle to Apache
* there is a RELEASE90 on Maven, see for example https://search.maven.org/artifact/org.netbeans.modules/org-netbeans-core/RELEASE90/jar

Do you see any cons to update?

**Comment by eduramiba** [comment]
Thanks @mcallisto Yeah, we need to update Gephi dependencies to netbeans so they now user maven central (finally they are there :smile: ). We will use RELEASE110 or whatever is current version when we do it.

For example:
https://mvnrepository.com/artifact/org.netbeans.modules/org-netbeans-modules-masterfs/RELEASE110

Adding to 0.9.3 milestone

**Comment by mcallisto** [comment]
Thank you @eduramiba for the quick reply! Look forward to 0.9.3

**Comment by tschoellhorn** [comment]
@eduramiba we have the same issue - the repository http://bits.netbeans.org/nexus/content/groups/netbeans/ is currently down. 

I wonder if it might be even easier if the packaging of the Toolkit could use the Shade-Plugin of maven. This way the old version of the netbeans could still be used but the Toolkit did not have the "externel" dependencies. 

As a side note: we are using the Toolkit in a project where we do not use any other dependencies of NetBeans. 

Otherwise I would be happy for a new release of the Toolkit!

**Comment by seinecle** [comment]
Did anyone find a way to upgrade to a newest release of NetBeans? I am trying to add the Gephi Toolkit to a java modular project and I hit a split package because of NetBeans:

`java.lang.module.ResolutionException: Modules org.openide.util.lookup.RELEASE82 and org.openide.util.RELEASE82 export package org.netbeans.modules.openide.util to module preview.api`

**Comment by liuqiyuan** [comment]
Any updates here?

**Comment by eduramiba** [comment]
This will be fixed once gephi 0.9.3 is released, which uses latest version in maven central.

**Comment by liuqiyuan** [comment]
Thanks for the prompt reply Eduardo! May we know the road map of the 0.9.3 release? Really looking forward to it!

**Comment by liuqiyuan** [comment]
Happy New Year! Any updates here? :)

**Comment by mbastian** [comment]
Thanks, this is now fixed in `master` and in sync with the upcoming Gephi 0.9.3 version. It relies on the `RELEASE130` version of Netbeans Platform. Once the Gephi 0.9.3 version is released, we'll also make a gephi-toolkit release.
